language: ruby
dist: bionic
services:
  - postgresql
env:
  matrix:
    - DATABASE_ADAPTER=sqlite3
    - DATABASE_ADAPTER=postgresql
rvm:
  - 2.7.2
  - 2.6.6
  - 2.5.8
gemfile:
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_0.gemfile
cache:
  directories:
    - /home/travis/.rvm/gems/ruby-2.7.2
    - /home/travis/.rvm/gems/ruby-2.6.6
    - /home/travis/.rvm/gems/ruby-2.5.8
install: "bundle install --jobs=3 --retry=3"
script: "bundle exec rake"
branches:
  only:
    - master
