name: RuboCop

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        ports: ["5432:5432"]

    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7]
        db: [sqlite3, postgresql]
        gemfile: [gemfiles/rails_6_0.gemfile]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: ../vendor/bundle
        key: ${{ runner.os }}-${{ runner.ruby }}--gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-rubocop-
      env:
        DATABASE_ADAPTER: ${{ matrix.db }}
        BUNDLE_GEMFILE: "${{ matrix.gemfile }}"

    - name: Install gems
      env:
        DATABASE_ADAPTER: ${{ matrix.db }}
        BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
      run: |
        bundle config path ../vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Run RuboCop
      env:
        DATABASE_ADAPTER: ${{ matrix.db }}
        BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
      run: bundle exec rubrake
