name: Tests
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7]
        db: [sqlite3, postgresql]
        gemfile: [gemfiles/rails_6_0.gemfile]
    runs-on: ubuntu-latest
    services:
      postgresql:
        image: postgres:latest
        ports: ["5432:5432"]
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-ruby-${{ matrix.ruby }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-ruby-${{ matrix.ruby }}-gems-
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Test
      env:
        DATABASE_ADAPTER: ${{ matrix.db }}
        BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
        PGHOST: 127.0.0.1
        PGUSER: postgres
        RAILS_ENV: test
        BUNDLE_PATH: 'vendor/bundle'
        GEM_HOME: 'vendor/bundle'
      run: |
        bundle exec rake
